### ISSUE TITLE
Alias `encrypt` to `add`

### ISSUE THREAD

**Issue by blimmer** [Ibotta/sopstool#10]
## Current Behavior

```console
sopstool encrypt secrets/foo.yaml

Error: unknown command "encrypt" for "sopstool"

Did you mean this?
	decrypt

Run 'sopstool --help' for usage.
unknown command "encrypt" for "sopstool"

Did you mean this?
	decrypt
```

## Expected Behavior

It would be kind of nice if this did the same thing as `add`. It feels like a natural parallel to `sopstool decrypt`.

## Steps to reproduce

linux, sopstool 0.1.0

**Comment by onyxraven** [comment]
This was done in #18
